### ISSUE TITLE
Should rave-node-process be a dependency?

### ISSUE THREAD

**Issue by briancavalier** [KidkArolis/rave-load-jsx#7]
I used rave-load-jsx today and had to install [rave-node-process](https://github.com/KidkArolis/rave-node-process) also, or else jsx transpiling would fail with an error (basically that `process` was undefined).  Should rave-load-jsx list rave-node-process as a dependency?  Or did I do something wrong?

FWIW, after I installed rave-node-process, it all worked perfectly ... made it really easy to create a simple demo with React :)

**Comment by unscriptable** [comment]
ping :)  We're writing a blog post that uses this project and it'd be great if it _just worked_.

**Comment by KidkArolis** [comment]
Yeah, we could do that. Is listing it as dep enough for rave to load it? Or should "process-browser" be required in this extension.

**Comment by briancavalier** [comment]
I didn't need to do anything other than `npm install --save rave-node-process` to make stuff work, so I think just listing it as a dep should be enough.

**Comment by unscriptable** [comment]
yep. it declares the global as part of the extension create() function.
